# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=200)),
                ('manufacturing_company', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_property', models.CharField(max_length=200)),
                ('unit_of_measurement', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=200, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartpollution.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lower_trigger', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('upper_trigger', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartpollution.Metric')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartpollution.Template')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='metrics',
            field=models.ManyToManyField(to='smartpollution.Metric'),
        ),
    ]
