# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartpollution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=200)),
                ('manufacturing_company', models.CharField(max_length=200)),
            ],
        ),
    ]
