# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartpollution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_name', models.CharField(max_length=200, null=True)),
                ('contract_address', models.CharField(max_length=42, null=True)),
            ],
        ),
    ]
