# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartpollution', '0002_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_abi',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
