# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartpollution', '0002_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_property', models.CharField(max_length=200)),
                ('unit_of_measurement', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='metrics',
            field=models.ManyToManyField(to='smartpollution.Metric'),
        ),
    ]
