# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-18 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartpollution', '0003_contract_contract_abi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threshold',
            name='lower_trigger',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='upper_trigger',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
