# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartpollution', '0004_auto_20170618_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='gas_estimate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
