# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartpollution', '0004_template_tresholds'),
    ]

    operations = [
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lower_trigger', models.DecimalField(decimal_places=10, max_digits=19)),
                ('upper_trigger', models.DecimalField(decimal_places=10, max_digits=19)),
                ('metric_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartpollution.Metric')),
                ('template_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartpollution.Template')),
            ],
        ),
        migrations.RemoveField(
            model_name='tresholds',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='tresholds',
            name='metric_id',
        ),
        migrations.DeleteModel(
            name='Tresholds',
        ),
    ]
