# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartpollution', '0005_auto_20170428_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='device_id',
            new_name='device',
        ),
        migrations.RenameField(
            model_name='threshold',
            old_name='metric_id',
            new_name='metric',
        ),
        migrations.RenameField(
            model_name='threshold',
            old_name='template_id',
            new_name='template',
        ),
    ]
