# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartpollution', '0005_template_gas_estimate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='gas_estimate',
            new_name='gas_estimate_no_threshold',
        ),
        migrations.AddField(
            model_name='template',
            name='gas_estimate_with_threshold',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
