# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-30 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartpollution', '0006_auto_20170619_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='gas_estimate_no_threshold',
            new_name='gas_estimate_no_thres',
        ),
        migrations.RenameField(
            model_name='template',
            old_name='gas_estimate_with_threshold',
            new_name='gas_estimate_thres',
        ),
    ]
