# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartpollution', '0007_auto_20170501_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threshold',
            name='lower_trigger',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='upper_trigger',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True),
        ),
    ]
