# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartpollution', '0008_auto_20170501_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='template_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
